[project]
drom-version = "0.1"

[project]
authors = ["Fabrice Le Fessant <fabrice.le_fessant@origin-labs.com>"]
ci-systems = ["ubuntu-latest"]
copyright = "OCamlPro SAS & Origin Labs SAS"
edition = "4.10.0"
github-organization = "ocamlpro"
license = "LGPL2"
min-edition = "4.08.0"
name = "freeton-ocaml-sdk"
synopsis = "The freeton-ocaml-sdk project"
version = "0.1.0"

# keys that you could also define:
# odoc-target = "...odoc-target..."
# sphinx-target = "...sphinx-target..."
# archive = "...archive..."
# dev-repo = "...dev-repo..."
# bug-reports = "...bug-reports..."
# doc-api = "...doc-api..."
# doc-gen = "...doc-gen..."
# homepage = "...homepage..."

[project]
description = """
This project implements an OCaml binding to the TON-SDK and a set of tools
in OCaml to interact with Free TON, in particular the 'ft' command-line 
wallet.
"""

[project]
skip = ["src/ton_lib/main.ml", "src/freeton-ocaml-sdk/lib.rs", "src/ft/main.ml", "src/ft_lib/main.ml", "src/freeton-ocaml-sdk/main.ml", "sphinx/index.rst", "sphinx/install.rst"]

# project-wide library dependencies (not for package-specific deps)
[dependencies]

# project-wide tools dependencies (not for package-specific deps)
[tools.ocamlformat]
for-test = true
[tools.odoc]
for-doc = true
[tools.ppx_expect]
for-test = true
[tools.ppx_inline_test]
for-test = true

[project]

# dirs to skip while scanning for dune files
skip-dirs = []

# dirs to scan for share/ folders (with package names)
share-dirs = ["share"]

# build profile to use by default
# build-profile = ...

# Profile options for this project
#    [profile]
#    dev = { ocaml-flags = "-w +a-4-40-41-42-44" }
#    release = { ocaml-flags = "-w -a" }
[profile]
# ...

# project-wide fields (depends on project skeleton)
[fields]
dot-gitignore-trailer = """
Cargo.lock
"""

[[package]]
dir = "src/freeton-ocaml-sdk"
# edit 'src/freeton-ocaml-sdk/package.toml' for package-specific options

[[package]]
dir = "src/ft_lib"
# edit 'src/ft_lib/package.toml' for package-specific options

[[package]]
dir = "src/ft"
# edit 'src/ft/package.toml' for package-specific options

[[package]]
dir = "src/ton_lib"
# edit 'src/ton_lib/package.toml' for package-specific options

